export const REPO_LIST_REQUEST = 'REPO_LIST_REQUEST';
export const REPO_LIST_SUCCESS = 'REPO_LIST_SUCCESS';
export const REPO_LIST_FAIL = 'REPO_LIST_FAIL';

export const REPO_DETAILS_REQUEST = 'REPO_DETAILS_REQUEST';
export const REPO_DETAILS_SUCCESS = 'REPO_DETAILS_SUCCESS';
export const REPO_DETAILS_FAIL = 'REPO_DETAILS_FAIL';

export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCESS = 'SEARCH_SUCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';
